name: Build KeyTotem Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java Development Kit (JDK).
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: THE FINAL FIX - Convert line endings and set permissions.
      # This block makes the workflow completely robust.
      - name: Fix gradlew script
        run: |
          # This command strips the invisible Windows carriage returns (\r)
          sed -i 's/\r$//' ./gradlew
          # This command ensures the script is executable
          chmod +x ./gradlew

      # Step 4: Run the Gradle build command. This will now finally succeed.
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        
      # Step 5: Upload the compiled .jar file as a build artifact.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyTotem-1.21.5-Build
          path: build/libs/!(*-dev|*-sources).jar
