# A descriptive name for your workflow, which will appear in the "Actions" tab on GitHub.
name: Build KeyTotem Mod

# This section defines when the workflow will run.
on:
  # Run this workflow automatically every time you push code to the "main" branch.
  push:
    branches: [ "main" ]
  
  # This line allows you to manually trigger the workflow from the GitHub Actions page.
  workflow_dispatch:

# A workflow is made up of one or more jobs that run in sequence or in parallel.
jobs:
  # We define a single job called "build".
  build:
    # This job will run on the latest version of Ubuntu Linux provided by GitHub.
    runs-on: ubuntu-latest

    # A job is a sequence of steps.
    steps:
      # Step 1: Check out your repository's code.
      # The .gitattributes file you created ensures 'gradlew' has the correct permissions.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java Development Kit (JDK).
      # Minecraft 1.21.5 requires Java 21.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Run the Gradle build command.
      # The './gradlew build' command compiles the code and creates the .jar file.
      # We add '--stacktrace' to get more detailed error messages if something goes wrong.
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        
      # Step 4: Upload the compiled .jar file as a "build artifact".
      # This makes the final mod file downloadable from the workflow's summary page.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # This will be the name of the downloadable file.
          name: KeyTotem-1.21.5-Build
          # This tells the action where to find the file.
          # The pattern !(*-dev|*-sources).jar grabs the final mod jar and ignores others.
          path: build/libs/!(*-dev|*-sources).jar
