name: Build KeyTotem Mod
on:
push:
branches: [ "main" ]
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
  # Step 1: Check out the code.
  - name: Checkout repository
    uses: actions/checkout@v4

  # Step 2: Set up the correct Java version.
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'

  # Step 3: THE FIX - Explicitly make the gradlew script executable.
  # This step guarantees the script has the correct permissions inside the GitHub runner.
  - name: Make gradlew executable
    run: chmod +x ./gradlew

  # Step 4: Run the build command. This will now succeed.
  - name: Build with Gradle
    run: ./gradlew build --stacktrace
    
  # Step 5: Upload the final .jar file.
  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    with:
      name: KeyTotem-1.21.5-Build
      path: build/libs/!(*-dev|*-sources).jar
