name: Build KeyTotem Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java Development Kit (JDK).
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: THE FINAL FIX - Set up a specific, compatible version of Gradle.
      # This forces the runner to use Gradle 8.7, which works with Fabric Loom.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      # Step 4: Run the Gradle build command.
      - name: Build with Gradle
        run: gradle build --stacktrace
        
      # Step 5: Upload the compiled .jar file as a build artifact.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyTotem-1.21.5-Build
          path: build/libs/!(*-dev|*-sources).jar
